name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.10.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: 'app-test/package-lock.json'  
        working-directory: app-test
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
 
